<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martin Westberg">

<title>Martin_W_InsuranceWithR</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="R_notebook_files/libs/clipboard/clipboard.min.js"></script>
<script src="R_notebook_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="R_notebook_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="R_notebook_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="R_notebook_files/libs/quarto-html/popper.min.js"></script>
<script src="R_notebook_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="R_notebook_files/libs/quarto-html/anchor.min.js"></script>
<link href="R_notebook_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="R_notebook_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="R_notebook_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="R_notebook_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="R_notebook_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Martin_W_InsuranceWithR</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Martin Westberg </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="dataförståelse" class="level2">
<h2 class="anchored" data-anchor-id="dataförståelse">1. Dataförståelse</h2>
<p><strong>Läs in data:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># message och warning=FALSE, så undviks output av följande:</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"insurance_costs.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,100
Columns: 14
$ customer_id       &lt;chr&gt; "C100000", "C100001", "C100002", "C100003", "C100004…
$ age               &lt;dbl&gt; 48, 40, 50, 62, 39, 39, 63, 52, 36, 49, 36, 36, 45, …
$ sex               &lt;chr&gt; "female", "male", "female", "male", "female", "femal…
$ region            &lt;chr&gt; "east", "west", "south", "north", "east", "west", "e…
$ bmi               &lt;dbl&gt; 24.8, 29.5, 18.3, 25.5, 27.3, 23.3, 23.9, 24.8, 28.6…
$ children          &lt;dbl&gt; 0, 1, 2, 5, 2, 4, 3, 2, 0, 2, 2, 2, 1, 1, 1, 1, 0, 3…
$ smoker            &lt;chr&gt; "no", "no", "no", "yes", "no", "no", "no", "no", "no…
$ chronic_condition &lt;chr&gt; "no", "no", "no", "no", "no", "no", "no", "no", "yes…
$ exercise_level    &lt;chr&gt; "high", "medium", "high", "medium", "medium", "high"…
$ plan_type         &lt;chr&gt; "basic", "basic", "standard", "basic", "basic", "sta…
$ prior_accidents   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0…
$ prior_claims      &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 3, 0, 0, 0…
$ annual_checkups   &lt;dbl&gt; 1, 4, 3, NA, 0, 2, 1, 2, 3, 2, 3, 3, 4, 4, 2, 1, 2, …
$ charges           &lt;dbl&gt; 6439.10, 8274.06, 5190.99, 14500.35, 6534.40, 8026.3…</code></pre>
</div>
</div>
<p>Det är 1,100 observationer med 14 variabler, och datatyperna ska justeras:</p>
<ul>
<li>heltal, decimaltal, booleans och strängar.</li>
<li>det kan behövas filtrering eller ifyllnad, samt trim, lower, och title.</li>
</ul>
<p><strong>Se närmare på kolumner med saknade värden:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Antal NA per kolumn:</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># colSums(is.na(df_clean))</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">#     anger att: bmi, exercise_level, annual_checkups har NaN.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Se över unique values i olika kolumner:</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># unique(df$exercise_level)</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(df<span class="sc">$</span>plan_type)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "basic"    "standard" "premium"  "Premium"  "Standard"</code></pre>
</div>
</div>
</section>
<section id="datastädning-och-förberedelse" class="level2">
<h2 class="anchored" data-anchor-id="datastädning-och-förberedelse">2. Datastädning och förberedelse</h2>
<p><strong>Åtgärder i städning:</strong></p>
<ul>
<li>Kundnummer görs till heltal genom att först ta bort “C”.</li>
<li>Vid NaN: BMI och årliga besök får median insatt, och träningsnivå får <code>unknown</code>.</li>
<li>Gör “Ja/Nej” till logisk.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"script1_cleaning.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Nya variabler och konvertera <em>chr</em> till <em>fct</em>:</strong></p>
<ul>
<li>Skapa kolumner med <em>if_else</em> och <em>case_when</em> som följer kriterier, så fås olika grupper. Även <code>historic_score</code> via addition av tidigare olyckor samt fordringar.</li>
<li>Det görs även en lista med kategoriska kolumner (som är städade redan), sen en funktion som sätter <em>as.factor</em>, sen kallas den och skriver över resultatet till <code>df_clean</code>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary visar vanliga värden, så kan man välja numeriska gränser i kategori variabler.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(df_clean$bmi)</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"script2_createVar_andFactor.R"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,100
Columns: 19
$ customer_id       &lt;int&gt; 100000, 100001, 100002, 100003, 100004, 100005, 1000…
$ age               &lt;int&gt; 48, 40, 50, 62, 39, 39, 63, 52, 36, 49, 36, 36, 45, …
$ sex               &lt;fct&gt; female, male, female, male, female, female, female, …
$ region            &lt;fct&gt; East, West, South, North, East, West, East, North, E…
$ bmi               &lt;dbl&gt; 24.8, 29.5, 18.3, 25.5, 27.3, 23.3, 23.9, 24.8, 28.6…
$ children          &lt;int&gt; 0, 1, 2, 5, 2, 4, 3, 2, 0, 2, 2, 2, 1, 1, 1, 1, 0, 3…
$ smoker            &lt;lgl&gt; FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALS…
$ chronic_condition &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…
$ exercise_level    &lt;fct&gt; High, Medium, High, Medium, Medium, High, High, Medi…
$ plan_type         &lt;fct&gt; Basic, Basic, Standard, Basic, Basic, Standard, Basi…
$ prior_accidents   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0…
$ prior_claims      &lt;int&gt; 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 3, 0, 0, 0…
$ annual_checkups   &lt;int&gt; 1, 4, 3, 2, 0, 2, 1, 2, 3, 2, 3, 3, 4, 4, 2, 1, 2, 1…
$ charges           &lt;dbl&gt; 6439.10, 8274.06, 5190.99, 14500.35, 6534.40, 8026.3…
$ bmi_class         &lt;fct&gt; Normal, Overweight, Underweight, Normal, Overweight,…
$ historic_score    &lt;int&gt; 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 1, 3, 0, 0, 0…
$ risk_level        &lt;fct&gt; Low, Low, Low, High, Low, Low, Low, Low, High, High,…
$ age_group         &lt;fct&gt; Middle Age, Young Adult, Middle Age, Senior, Young A…
$ exercises_checks  &lt;fct&gt; Healthy, Less Healthy, Healthy, Less Healthy, Less H…</code></pre>
</div>
</div>
<p>Nu har vi factor som datatyp för kategorier, så <em>dplyr</em> hanterar grupperingar väl.</p>
<p>De nya variablerna <code>bmi_class</code>, <code>historic_score</code>, <code>risk_level</code>, <code>age_group</code>, <code>exercise_checks</code> ger regressionsmodellering yta att undersöka om olika profiler är kopplade till större betalning.</p>
</section>
<section id="beskrivande-analys" class="level2">
<h2 class="anchored" data-anchor-id="beskrivande-analys">3. Beskrivande analys</h2>
<section id="betalning-bland-åldergrupper" class="level3">
<h3 class="anchored" data-anchor-id="betalning-bland-åldergrupper">3.1 Betalning bland åldergrupper</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ladda script 3 och visa output för åldergrupper</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"script3_descriptive_analysis.R"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>age_grouped <span class="co"># stigande ordning: medelvärde.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  age_group   mean_charge median_charge     n proportion_pct
  &lt;fct&gt;             &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt;          &lt;dbl&gt;
1 Junior            8337.         7884.    44            4  
2 Young Adult       9076.         8103.   432           39.3
3 Middle Age       10550.         9758.   527           47.9
4 Senior           12566.        11166.    97            8.8</code></pre>
</div>
</div>
<p>De flesta är inte äldre än 60 eller yngre än 20. Även syns att betalningar ökar i snitt och median med ålder.</p>
</section>
<section id="betalning-bland-bmi-kategori" class="level3">
<h3 class="anchored" data-anchor-id="betalning-bland-bmi-kategori">3.2 Betalning bland bmi-kategori</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bmi_grouped <span class="co"># stigande (mean)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  bmi_class   mean_charge median_charge std_charge proportion_pct
  &lt;fct&gt;             &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;
1 Underweight       9171.         8286.      4427.           22.9
2 Normal            9854.         8896.      4484.           22.6
3 Overweight       10139.         9168.      4337.           29.9
4 Obese            10985.         9910.      4907.           24.5</code></pre>
</div>
</div>
<p>De med mer än 30.5 och mindre än 16 i bmi betalar mer och mindre, respektivt, än normal- och överviktiga. En föraning är att kostnader har större skillnader för de två mitten bmi-klasserna (och ålder) med ursprung i andra led. Övergripande stiger kostnader med bmi-klass.</p>
</section>
<section id="betalning-inom-rökning" class="level3">
<h3 class="anchored" data-anchor-id="betalning-inom-rökning">3.3 Betalning inom rökning</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>smoker_grouped <span class="co"># fallande (mean)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  smoker mean_charge median_charge proportion_pct
  &lt;lgl&gt;        &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;
1 TRUE        16537.        16392.           18.5
2 FALSE        8586.         8232.           81.5</code></pre>
</div>
</div>
<p>Rökare betalar det dubbla, medan de motsvarar 18.5%.</p>
</section>
<section id="betalning-bland-rökare-och-kroniska" class="level3">
<h3 class="anchored" data-anchor-id="betalning-bland-rökare-och-kroniska">3.4 Betalning bland rökare och kroniska</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>smoker_chronic <span class="co"># fallande (proportion)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  smoker chronic_condition mean_charge median_charge std_charge proportion_pct
  &lt;lgl&gt;  &lt;lgl&gt;                   &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;
1 FALSE  FALSE                   7554.         7467.      2569.           62.5
2 FALSE  TRUE                   11978.        11871.      3046.           19  
3 TRUE   FALSE                  15444.        14652.      3411.           13.2
4 TRUE   TRUE                   19224.        18883.      3282.            5.4</code></pre>
</div>
</div>
<p>Medan nästan 63% varken är kroniska eller rökare, indikeras stigande kostnader (medel) för drabbade från cirka 7500 till 19200.</p>
</section>
<section id="visualer" class="level3">
<h3 class="anchored" data-anchor-id="visualer">3.5 Visualer</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"script4_visuals.R"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># åldersgrupp col plot</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>ageplot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_notebook_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Betalning tycks öka med åldersgrupp, särskilt när senior.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bmi-klasser col plot</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>bmiplot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_notebook_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Betalning tycks öka med bmi-klass, men de två i mitten betalar nästan lika.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># true/false col plot</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>smoke_chron_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_notebook_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Bland rökare, betalar kroniska mera, samma gäller icke-rökare. Samtidigt är rökande status led till högre betalning också. Är profilen ej rökande eller kronisk så betalar denna ungefär hälften eller en tredjedel av de andra profilerna.</p>
<p>I helhet tycks ålder eller vikt inte driva skillnader i betalning mest, utan övriga faktorer såsom rökare och kroniska, där differenser i pris är framstående. Vad som antyds är att rökning är en kritisk risk som bör rättfärdiga en högre försäkringskostnad. Rökning och övriga faktorer gås igenom i regressionsanalysen.</p>
</section>
</section>
<section id="regressionsanalys" class="level2">
<h2 class="anchored" data-anchor-id="regressionsanalys">4. Regressionsanalys</h2>
<p>Vilka features som leder mest till prissättningarna ska nu fokuseras på. I initiell analys syntes liknelser och skillnader emellan profiler, men helheten i sambanden är inte klarlagt. Är det så att risker går upp i steg som från vuxen till senior, eller numeriskt (kontinuerligt); jämförelse av olikt designade regressionsmodeller följer, efter ett inledande hypotestest.</p>
<section id="hypotestest" class="level3">
<h3 class="anchored" data-anchor-id="hypotestest">4.1 Hypotestest</h3>
<p>Om binära och numeriska variabler har stor påverkan på pris var för sig, så kan p-värde och konfidensintervall indikera viktigheten i tvåsticksprov Welch t-test. ANOVA hanterar ickebinära och görs inte i detta arbetet. T-testets isolerande prövning blir uppföljt av multipel regression efteråt vilket fångar variablernas samspel.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Välj rökare, kroniska, hälsovanor och risknivå-variablerna, då de kan vara hälsokritiska.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>t_test_smoker <span class="ot">&lt;-</span> <span class="fu">t.test</span>(charges <span class="sc">~</span> smoker, <span class="at">data =</span> df_clean)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>t_test_chronic <span class="ot">&lt;-</span> <span class="fu">t.test</span>(charges <span class="sc">~</span> chronic_condition, <span class="at">data =</span> df_clean)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>t_test_exerciseschecks <span class="ot">&lt;-</span> <span class="fu">t.test</span>(charges <span class="sc">~</span> exercises_checks, <span class="at">data =</span> df_clean)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>t_test_risklevel <span class="ot">&lt;-</span> <span class="fu">t.test</span>(charges <span class="sc">~</span> risk_level, <span class="at">data =</span> df_clean)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>t_test_smoker</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  charges by smoker
t = -27.771, df = 276.46, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
95 percent confidence interval:
 -8514.891 -7387.624
sample estimates:
mean in group FALSE  mean in group TRUE 
           8585.889           16537.147 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t_test_chronic</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># t_test_exerciseschecks</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># t_test_risklevel</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>t-test resultat:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variabel</th>
<th>t-värde</th>
<th>95% konfidensintervall</th>
<th>Effekt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>smoker</code></td>
<td>-27.7</td>
<td>(-8514, -7387)</td>
<td>Rökare betalar mer</td>
</tr>
<tr class="even">
<td><code>chronic_condition</code></td>
<td>-15.5</td>
<td>(-5231, -4057)</td>
<td>Kroniskt drabbade betalar mer</td>
</tr>
<tr class="odd">
<td><code>exercises_checks</code></td>
<td>-4.8</td>
<td>(-2141, -893)</td>
<td>Mindre hälsosamma betalar mer</td>
</tr>
<tr class="even">
<td><code>risk_level</code></td>
<td>24.1</td>
<td>(4801, 5654)</td>
<td>Högriskkunder betalar mer</td>
</tr>
</tbody>
</table>
<p>Notera att ordningen på true och false orsakar minustecknet, medan effekten beskriver ordningen. Siffran noll var inte med i konfidensintervallen, och så var <em>p</em> &lt; 0.001 i alla granskningar; statistiskt signifikant.</p>
<p>Framträdelsevis är <code>smoker</code> den status som leder till störst betalningsskillnad, sett i magnituden av intervallet. Sen följer av kronisk, risknivå (vilken består av bl.a. rökare och kronisk) och sist hälsovanor. Hälsovanor kan tolkas vara kompletterande för hälsan, medan status av rökning och kronisk har större avgörande (och därmed borde tas med i regressionen).</p>
</section>
<section id="modellering" class="level3">
<h3 class="anchored" data-anchor-id="modellering">4.2 Modellering</h3>
<p>Vi gör två modeller (en med orginella variabler och en med anpassade) och undersöker resultaten om pris följer räta förhållanden. Variabeln <code>risk_level</code> är gjord med bmi, rök- och kronisk-status, så den tas inte med för multikolineäritet riskerar skeva resultaten.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modell 1, med age, bmi, smoker och kronisk.</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> smoker <span class="sc">+</span> chronic_condition, <span class="at">data =</span> df_clean)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + smoker + chronic_condition, 
    data = df_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-10052.0  -1649.1   -117.3   1571.5  17803.5 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           -129.059    533.197  -0.242    0.809    
age                     75.919      6.254  12.140   &lt;2e-16 ***
bmi                    164.978     17.013   9.697   &lt;2e-16 ***
smokerTRUE            7747.191    198.193  39.089   &lt;2e-16 ***
chronic_conditionTRUE 4100.990    180.041  22.778   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2550 on 1095 degrees of freedom
Multiple R-squared:  0.6904,    Adjusted R-squared:  0.6893 
F-statistic: 610.5 on 4 and 1095 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Modell 1 har <span class="math inline">\(R^2\)</span> á 69%, <em>p</em> &lt; 0.001, och residual standardfel: 2550. De fyra koefficienterna har <em>p</em> &lt; 0.001.</p>
<p>En negativ intercept när features antas vara noll (modell 1) beror på matematik, och basvärdet för kategorier är antagna.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modell 2, med skapta variabler (ej risk_level)</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age_group <span class="sc">+</span> bmi_class <span class="sc">+</span> plan_type <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>               historic_score <span class="sc">+</span> exercises_checks, <span class="at">data =</span> df_clean)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_group + bmi_class + plan_type + historic_score + 
    exercises_checks, data = df_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-10149.2  -2899.2   -992.8   2232.7  22841.2 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    5875.3      746.9   7.866 8.79e-15 ***
age_groupMiddle Age            1894.3      657.6   2.881 0.004046 ** 
age_groupSenior                3706.2      761.1   4.870 1.28e-06 ***
age_groupYoung Adult            557.9      662.8   0.842 0.400129    
bmi_classObese                 1193.2      368.6   3.237 0.001245 ** 
bmi_classOverweight             274.8      352.4   0.780 0.435738    
bmi_classUnderweight           -653.5      375.7  -1.740 0.082229 .  
plan_typePremium               1935.7      369.9   5.232 2.01e-07 ***
plan_typeStandard              1018.2      288.4   3.530 0.000433 ***
historic_score                 1467.1      158.0   9.288  &lt; 2e-16 ***
exercises_checksLess Healthy   1073.5      330.0   3.253 0.001176 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4171 on 1089 degrees of freedom
Multiple R-squared:  0.1764,    Adjusted R-squared:  0.1688 
F-statistic: 23.32 on 10 and 1089 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(df_clean<span class="sc">$</span>age_group) <span class="co"># första värdet är referenspunkten för koefficienter.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Junior"      "Middle Age"  "Senior"      "Young Adult"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(df_clean<span class="sc">$</span>bmi_class) <span class="co"># referenspunkterna: normal bmi, junior åldersgrupp.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Normal"      "Obese"       "Overweight"  "Underweight"</code></pre>
</div>
</div>
<p>Modell 2 har lägre <span class="math inline">\(R^2\)</span> á 16.9%, <em>p</em> &lt; 0.001, och högre residual standardfel: 4171, sämre predikerandes. Senior, intercept, historik, premium samt standard plan har <em>p</em> &lt; 0.001. Senior har 3908 kr ökning ifrån Junior.</p>
<p>Mindre förklarad varians hos den andra modellen föreslår att kategoriserande får precision att tappa, medan förklarbarhet med kategorier ökar i affärsnära nyttjande (och betalningsplan har i verklighet prisskillnader). Hur gränserna är dragna vid kategoriskapandet är avgörande, de var improviserade och osannolikt optimala, vilket regressionen framhäver. Segment kan bära fördel i affärsliv, men dessa kontinuerliga variabler ledde inte till en mer precis statistisk modell.</p>
</section>
<section id="felanalys" class="level3">
<h3 class="anchored" data-anchor-id="felanalys">4.3 Felanalys</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gör regressions- och residualgrafer</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"script5_regression.R"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 modellers faktiska och predikerade priser</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>regplot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_notebook_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Modell 1 visar mer närhet till <em>1:1 linjen</em>, medan modell 2 har större kluster under linjen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residualgraf</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>errplot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_notebook_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Residualer ligger balanserat över och under 0-linjen för modell 1, medan modell 2 har större spridning av fel och kluster under linjen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># QQplot modell 1</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(model1))</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(model1), <span class="at">col =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_notebook_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Första modellen har punkter nära referenslinjen för mestadelen, med lite flera uppgående outliers i höger.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># QQplot modell 2</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(model2))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(model2), <span class="at">col =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_notebook_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Andra modellen avviker mer från normalfördelning till vänster och höger med synlig skevhet.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>